using Machine.Specifications;
using Timtek.GitFlowVersioning.Generation;
using Timtek.GitFlowVersioning.Versioning;

namespace Timtek.GitFlowVersioning.Specs.Generation;

[Subject(typeof(GitVersionInformationGenerator))]
class when_generating_git_version_information_for_a_stable_release
{
    static VersionInfo versionInfo = null!;
    static string result = null!;

    Establish context = () => versionInfo = new VersionInfo
    {
        Major = "1",
        Minor = "2",
        Patch = "3",
        MajorMinorPatch = "1.2.3",
        PreReleaseLabel = string.Empty,
        PreReleaseLabelWithDash = string.Empty,
        PreReleaseNumber = string.Empty,
        PreReleaseTag = string.Empty,
        PreReleaseTagWithDash = string.Empty,
        SemVer = "1.2.3",
        FullSemVer = "1.2.3",
        BranchName = "main",
        EscapedBranchName = "main",
        Sha = "abcdef1234567890abcdef1234567890abcdef12",
        ShortSha = "abcdef1",
        BuildMetaData = "0",
        FullBuildMetaData = "0.Branch.main.Sha.abcdef1234567890abcdef1234567890abcdef12",
        InformationalVersion = "1.2.3+0.Branch.main.Sha.abcdef1234567890abcdef1234567890abcdef12",
        AssemblySemVer = "1.2.0.0",
        AssemblySemFileVer = "1.2.3.0"
    };

    Because of = () => result = GitVersionInformationGenerator.Generate(versionInfo);

    It should_contain_auto_generated_comment = () => result.ShouldContain("// <auto-generated />");
    It should_contain_class_declaration = () => result.ShouldContain("internal static class GitVersionInformation");
    It should_contain_major_constant = () => result.ShouldContain("public const string Major = \"1\";");
    It should_contain_minor_constant = () => result.ShouldContain("public const string Minor = \"2\";");
    It should_contain_patch_constant = () => result.ShouldContain("public const string Patch = \"3\";");
    It should_contain_semver_constant = () => result.ShouldContain("public const string SemVer = \"1.2.3\";");
    It should_contain_informational_version_constant = () => result.ShouldContain("public const string InformationalVersion = \"1.2.3+0.Branch.main.Sha.abcdef1234567890abcdef1234567890abcdef12\";");
    It should_contain_assembly_sem_ver_constant = () => result.ShouldContain("public const string AssemblySemVer = \"1.2.0.0\";");
}

[Subject(typeof(GitVersionInformationGenerator))]
class when_generating_git_version_information_for_alpha_prerelease
{
    static VersionInfo versionInfo = null!;
    static string result = null!;

    Establish context = () => versionInfo = new VersionInfo
    {
        Major = "1",
        Minor = "3",
        Patch = "0",
        MajorMinorPatch = "1.3.0",
        PreReleaseLabel = "alpha",
        PreReleaseLabelWithDash = "-alpha",
        PreReleaseNumber = "7",
        PreReleaseTag = "alpha.7",
        PreReleaseTagWithDash = "-alpha.7",
        SemVer = "1.3.0-alpha.7",
        FullSemVer = "1.3.0-alpha.7+7",
        BranchName = "develop",
        EscapedBranchName = "develop",
        Sha = "abcdef1234567890abcdef1234567890abcdef12",
        ShortSha = "abcdef1",
        BuildMetaData = "7",
        FullBuildMetaData = "7.Branch.develop.Sha.abcdef1234567890abcdef1234567890abcdef12",
        InformationalVersion = "1.3.0-alpha.7+7.Branch.develop.Sha.abcdef1234567890abcdef1234567890abcdef12",
        AssemblySemVer = "1.3.0.0",
        AssemblySemFileVer = "1.3.0.0"
    };

    Because of = () => result = GitVersionInformationGenerator.Generate(versionInfo);

    It should_contain_prerelease_label = () => result.ShouldContain("public const string PreReleaseLabel = \"alpha\";");
    It should_contain_prerelease_tag = () => result.ShouldContain("public const string PreReleaseTag = \"alpha.7\";");
    It should_contain_semver_with_prerelease = () => result.ShouldContain("public const string SemVer = \"1.3.0-alpha.7\";");
}

[Subject(typeof(GitVersionInformationGenerator), "string escaping")]
class when_generating_git_version_information_with_branch_name_containing_special_characters
{
    static VersionInfo versionInfo = null!;
    static string result = null!;

    Establish context = () => versionInfo = new VersionInfo
    {
        Major = "1",
        Minor = "0",
        Patch = "0",
        MajorMinorPatch = "1.0.0",
        PreReleaseLabel = "alpha",
        PreReleaseLabelWithDash = "-alpha",
        PreReleaseNumber = "1",
        PreReleaseTag = "alpha.1",
        PreReleaseTagWithDash = "-alpha.1",
        SemVer = "1.0.0-alpha.1",
        FullSemVer = "1.0.0-alpha.1+1",
        BranchName = "feature/test\"branch",
        EscapedBranchName = "feature-test\"branch",
        Sha = "abc123",
        ShortSha = "abc123",
        BuildMetaData = "1",
        FullBuildMetaData = "1.Branch.feature-test-branch.Sha.abc123",
        InformationalVersion = "1.0.0-alpha.1+1.Branch.feature-test\\branch.Sha.abc123",
        AssemblySemVer = "1.0.0.0",
        AssemblySemFileVer = "1.0.0.0"
    };

    Because of = () => result = GitVersionInformationGenerator.Generate(versionInfo);

    It should_produce_compilable_csharp_by_escaping_double_quotes =
        () => result.ShouldContain("public const string BranchName = \"feature/test\\\"branch\";");

    It should_escape_backslash_in_informational_version =
        () => result.ShouldContain("public const string InformationalVersion = \"1.0.0-alpha.1+1.Branch.feature-test\\\\branch.Sha.abc123\";");
}
