using Timtek.GitFlowVersioning.Versioning;

namespace Timtek.GitFlowVersioning.Generation;

/// <summary>Generates the <c>GitVersionInformation.g.cs</c> source file content.</summary>
public static class GitVersionInformationGenerator
{
    /// <summary>Generates the C# source for the <c>GitVersionInformation</c> static class.</summary>
    /// <param name="versionInfo">The computed version info to embed.</param>
    /// <returns>The complete C# source file content as a string.</returns>
    public static string Generate(VersionInfo versionInfo)
    {
        return $@"// <auto-generated />
// Generated by Timtek.GitFlowVersioning - do not edit manually.
using System.Runtime.CompilerServices;

[CompilerGenerated]
internal static class GitVersionInformation
{{
    public const string Major = ""{Escape(versionInfo.Major)}"";
    public const string Minor = ""{Escape(versionInfo.Minor)}"";
    public const string Patch = ""{Escape(versionInfo.Patch)}"";
    public const string PreReleaseLabel = ""{Escape(versionInfo.PreReleaseLabel)}"";
    public const string PreReleaseLabelWithDash = ""{Escape(versionInfo.PreReleaseLabelWithDash)}"";
    public const string PreReleaseNumber = ""{Escape(versionInfo.PreReleaseNumber)}"";
    public const string PreReleaseTag = ""{Escape(versionInfo.PreReleaseTag)}"";
    public const string PreReleaseTagWithDash = ""{Escape(versionInfo.PreReleaseTagWithDash)}"";
    public const string BranchName = ""{Escape(versionInfo.BranchName)}"";
    public const string EscapedBranchName = ""{Escape(versionInfo.EscapedBranchName)}"";
    public const string Sha = ""{Escape(versionInfo.Sha)}"";
    public const string ShortSha = ""{Escape(versionInfo.ShortSha)}"";
    public const string MajorMinorPatch = ""{Escape(versionInfo.MajorMinorPatch)}"";
    public const string SemVer = ""{Escape(versionInfo.SemVer)}"";
    public const string FullSemVer = ""{Escape(versionInfo.FullSemVer)}"";
    public const string BuildMetaData = ""{Escape(versionInfo.BuildMetaData)}"";
    public const string FullBuildMetaData = ""{Escape(versionInfo.FullBuildMetaData)}"";
    public const string InformationalVersion = ""{Escape(versionInfo.InformationalVersion)}"";
    public const string AssemblySemVer = ""{Escape(versionInfo.AssemblySemVer)}"";
    public const string AssemblySemFileVer = ""{Escape(versionInfo.AssemblySemFileVer)}"";
}}
";
    }

    /// <summary>Generates the C# source for the assembly info attributes file.</summary>
    /// <param name="versionInfo">The computed version info to embed.</param>
    /// <returns>The complete C# source file content as a string.</returns>
    public static string GenerateAssemblyInfo(VersionInfo versionInfo)
    {
        return $@"// <auto-generated />
// Generated by Timtek.GitFlowVersioning - do not edit manually.
using System.Reflection;

[assembly: AssemblyVersion(""{Escape(versionInfo.AssemblySemVer)}"")]
[assembly: AssemblyFileVersion(""{Escape(versionInfo.AssemblySemFileVer)}"")]
[assembly: AssemblyInformationalVersion(""{Escape(versionInfo.InformationalVersion)}"")]
";
    }

    /// <summary>Escapes a value for safe embedding inside a C# verbatim string literal.</summary>
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", "");
}
