using Timtek.GitFlowVersioning.Versioning;

namespace Timtek.GitFlowVersioning.Generation;

/// <summary>Generates the <c>GitVersionInformation.g.cs</c> source file content.</summary>
public static class GitVersionInformationGenerator
{
    /// <summary>Generates the C# source for the <c>GitVersionInformation</c> static class.</summary>
    /// <param name="versionInfo">The computed version info to embed.</param>
    /// <returns>The complete C# source file content as a string.</returns>
    public static string Generate(VersionInfo versionInfo)
    {
        return $@"// <auto-generated />
// Generated by Timtek.GitFlowVersioning - do not edit manually.
using System.Runtime.CompilerServices;

[CompilerGenerated]
internal static class GitVersionInformation
{{
    public const string Major = ""{versionInfo.Major}"";
    public const string Minor = ""{versionInfo.Minor}"";
    public const string Patch = ""{versionInfo.Patch}"";
    public const string PreReleaseLabel = ""{versionInfo.PreReleaseLabel}"";
    public const string PreReleaseLabelWithDash = ""{versionInfo.PreReleaseLabelWithDash}"";
    public const string PreReleaseNumber = ""{versionInfo.PreReleaseNumber}"";
    public const string PreReleaseTag = ""{versionInfo.PreReleaseTag}"";
    public const string PreReleaseTagWithDash = ""{versionInfo.PreReleaseTagWithDash}"";
    public const string BranchName = ""{versionInfo.BranchName}"";
    public const string EscapedBranchName = ""{versionInfo.EscapedBranchName}"";
    public const string Sha = ""{versionInfo.Sha}"";
    public const string ShortSha = ""{versionInfo.ShortSha}"";
    public const string MajorMinorPatch = ""{versionInfo.MajorMinorPatch}"";
    public const string SemVer = ""{versionInfo.SemVer}"";
    public const string FullSemVer = ""{versionInfo.FullSemVer}"";
    public const string BuildMetaData = ""{versionInfo.BuildMetaData}"";
    public const string FullBuildMetaData = ""{versionInfo.FullBuildMetaData}"";
    public const string InformationalVersion = ""{versionInfo.InformationalVersion}"";
    public const string AssemblySemVer = ""{versionInfo.AssemblySemVer}"";
    public const string AssemblySemFileVer = ""{versionInfo.AssemblySemFileVer}"";
}}
";
    }

    /// <summary>Generates the C# source for the assembly info attributes file.</summary>
    /// <param name="versionInfo">The computed version info to embed.</param>
    /// <returns>The complete C# source file content as a string.</returns>
    public static string GenerateAssemblyInfo(VersionInfo versionInfo)
    {
        return $@"// <auto-generated />
// Generated by Timtek.GitFlowVersioning - do not edit manually.
using System.Reflection;

[assembly: AssemblyVersion(""{versionInfo.AssemblySemVer}"")]
[assembly: AssemblyFileVersion(""{versionInfo.AssemblySemFileVer}"")]
[assembly: AssemblyInformationalVersion(""{versionInfo.InformationalVersion}"")]
";
    }
}
